### ISSUE TITLE
Ideal settings for env?

### ISSUE THREAD

**Issue by 9mm** [heroku/heroku-buildpack-pgbouncer#123]
I'm looking to deploy this in production. I had a few questions

1. If I have my procfile like this: `web: bin/start-pgbouncer bundle exec puma -C config/puma.rb`, and in my `heroku config:set` I set `PGBOUNCER_MAX_CLIENT_CONN` and `PGBOUNCER_DEFAULT_POOL_SIZE` is that OK, or must they be set with `web: env PGBOUNCER_DEFAULT_POOL_SIZE=X bin/start-pgbouncer bundle exec puma -C`

2. As far as the best values, I'm assuming `PGBOUNCER_DEFAULT_POOL_SIZE` should be just short of the total # of database connections allowed for that heroku resource (so if you're on free plan which allows 20 connections, it should be PGBOUNCER_DEFAULT_POOL_SIZE=18`. As for `PGBOUNCER_MAX_CLIENT_CONN` I'm not sure whats ideal for this... my app IS single-threaded (1 thread per Puma, 1 thread per job que workers). That means for each instance of my app I have:

* `WEB_CONCURRENC=5` (puma workers)
* `RAILS_MAX_THREADS=1` (puma threads, database connection pool size PER rails instance)

Does that mean `PGBOUNCER_MAX_CLIENT_CONN` should also be 1 considering each instance of my app running (for both puma and jobs) is always 1 database connection/1 thread?

**Comment by 9mm** [comment]
I currently have `PGBOUNCER_DEFAULT_POOL_SIZE=16` and `PGBOUNCER_MAX_CLIENT_CONN=2` (just a guess on that one). But when I refresh the app a bunch (on a heroku DB that allows 20 connections) it is still allowing more than 16 connections. What am I missing?

I'm using 30 dynos to test.

**Comment by 9mm** [comment]
BTW in case its not clear, my main use case is to try to get to the point where I can deploy 300 dynos to deal with volume even though my database might only support 100 open connections.

I can't enable threading in my app because a lot of libraries I'm using aren't thread safe, so I'm stuck scaling dynos instead of threads.

**Comment by mble** [comment]
Hey @9mm 👋,

1. Setting it as a config variable works. Some folks like to use `PGBOUNCER_DEFAULT_POOL_SIZE=X` directly in the Procfile when each process type uses a different default pool size.
2. `default_pool_size` will be the pool of connections maintained between a dyno and the database instance.
`max_client_conn` is the maximum number of connections your database clients can make to the PgBouncer process. It can be helpful to refer to the documentation on this: https://pgbouncer.github.io/config.html. Having set as 1 is OK if each Puma process only opens a single connection.
3. It would still have more than 16 connections because the buildpack is deployed per dyno. The general maths to apply is `(PGBOUNCER_RESERVE_POOL_SIZE + PGBOUNCER_DEFAULT_POOL_SIZE) * number of dynos <= postgres max_connections`. So if you only had a pool size of 1, for a free database the max number of dynos would still be 20.

For your use case (scaling horizontally with multiple dynos, rather than many connections per dyno), you could check out the Connection Pooling beta: https://devcenter.heroku.com/articles/postgres-connection-pooling. This is only available on `standard-0` and above.

**Comment by 9mm** [comment]
Ok I see, thanks for your help. I will read this over, much appreciated!
