### ISSUE TITLE
Version 1.15.0 causes errors `server closed the connection unexpectedly` when closing down Sidekiq worker dynos

### ISSUE THREAD

**Issue by damhonglinh** [heroku/heroku-buildpack-pgbouncer#150]
After yesterday deploy, we started to get a lot of ActiveRecord errors `server closed the connection unexpectedly`. 

After hours of investigating, narrowing down the cause, we found out it's because of the new version `1.15.0` of `pgbouncer` (or v0.8.0 of this buildpack), and the errors happen when we stop (scale down) or restart a Sidekiq worker dyno.

From the logs when restarting a dyno, it looks like pgbouncer process (in the new version) gets killed too soon, at the same time when Sidekiq processes are stopping so any running SQL queries are abruptly stopped. While for the previous version, pgbouncer process seems to get killed after Sidekiq processes have stoped, as expected.

Our questions:
- Any ideas why the new version 1.15.0 causes these errors? Because checking changelog of [the buildpack](https://github.com/heroku/heroku-buildpack-pgbouncer/compare/v0.7.0...v0.8.0) and of [pgbouncer](https://www.pgbouncer.org/changelog.html#pgbouncer-115x), we cannot find any suspects. 
- Any ideas how to fix this issue?
- Is there a way for us to lock in version 0.7.0 of this buildpack (v1.14.0 of pgbouncer) as we can't find any documentation about this.

Variants of these errors:
- `ActiveRecord::StatementInvalid: PG::UnableToSend: server closed the connection unexpectedly. This probably means the server terminated abnormally before or while processing the request.`
- `ActiveRecord::StatementInvalid: PG::ConnectionBad: PQconsumeInput() server closed the connection unexpectedly. This probably means the server terminated abnormally before or while processing the request`
- `ActiveRecord::StatementInvalid: PG::ConnectionBad: PQconsumeInput() SSL connection has been closed unexpectedly`

**Comment by honigc** [comment]
We're also encountering this same problem today. It's possible to [pin an unofficial buildpack to a specific tag or commit](https://devcenter.heroku.com/articles/buildpacks#buildpack-references), and using `https://github.com/heroku/heroku-buildpack-pgbouncer#v0.7.0` seems to work as a temporary fix.

**Comment by edmorley** [comment]
Did anyone figure out the cause of the issues with pgbouncer 1.15?

In order to fix #164 (for Heroku-22) we now need to upgrade to pgbouncer 1.17, and unless 1.16 or 1.17 happened to fix the issue here, it's going to occur again. One option would be to only use 1.17 on Heroku-22, however that means more differences between stacks which isn't ideal, as it adds more variables to consider when upgrading stack.

cc @beanieboi

**Comment by ezekg** [comment]
Any update on this?

**Comment by edmorley** [comment]
So it turns out that this buildpack patches pgbouncer to adjust its shutdown behaviour, and that the patch was missing for both the earlier 1.15.0 upgrade attempt, and the more recent 1.17.0 release. The reason for this is that the build script had a silent "fall back to no patches" behaviour if a version-specific patch was not found.

In #169 I've added the missing patchfile for 1.17.0, and also adjusted the build script such that it no longer has a silent fallback to no patches - which will prevent future pgbouncer upgrades from accidentally not including the patch.

**Comment by edmorley** [comment]
(But ultimately the real issue here is that this buildpack is only informally maintained by people who don't actively use it, and the buildpack has insufficient test coverage)
