### ISSUE TITLE
Add CI tests for actually running pgbouncer on each stack image

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-pgbouncer#165]
Whilst this repo has CI, it only comprises of bats tests, which don't actually run the pgbouncer binaries against the Heroku stack images. 

If they did do so, CI would have caught #164.

For prior art as to how to test on each stack, see any of:
https://github.com/heroku/heroku-buildpack-ci-redis/blob/master/bin/test.sh
https://github.com/heroku/heroku-buildpack-redis/blob/main/support/test.sh

**Comment by mble-sfdc** [comment]
I'm gonna take a look at doing this - it's a bit fiddly for a couple of reasons with pgbouncer, but should be feasible. I'll have to try with an older version of the buildpack on the newer stack to see if I can reproduce this without actually connecting to a Postgres on the backend.

**Comment by mble-sfdc** [comment]
So a simple "start pgbouncer and connect to the admin interface via a unix socket" doesn't trigger #164, because the TLS codepaths aren't triggered, so unfortunately not that simple. However, we can at least check the "starts and connects via a unix socket" functionality can work easily enough.

Maybe over TCP it will trigger the codepath that was generating the segfault? I'll have to check.
