### ISSUE TITLE
Heroku postgres followers

### ISSUE THREAD

**Issue by rainerborene** [heroku/heroku-buildpack-pgbouncer#4]
I'm currently using the Makara gem for read and write replication using Heroku Postgres followers. It would be great to add support for multiple databases.

**Comment by harishlakshmi** [comment]
@rainerborene I am trying to use the Makara gem with Heroku Postgres followers. Can you give in more details on how you have integrated the same with initializers. Thanks in advance.

**Comment by francois-tilkee** [comment]
Same here @rainerborene , could you make a Gist about your custom configuration to make it work with heroku?

**Comment by gregburek** [comment]
Please open a ticket with Heroku support so that they can look at your app and help you specifically. That will also allow the ruby and data teams to see if there is documentation we can create. The comments of a three year old closed issue is probably not the best place to leave the resolution of this problem.

**Comment by GaudamThiyagarajan** [comment]
There are literally no docs suggesting how to use pgbouncer with malaria. I am modifying currently database.yml to support Makara in Heroku but not sure how to enable pgbouncer with it.
