### ISSUE TITLE
disable stunnel?

### ISSUE THREAD

**Issue by josh-devops-center** [heroku/heroku-buildpack-pgbouncer#60]
Hi,

Is there a way to disable stunnel? We would like to be able to disable SSL when needed.

Thanks

**Comment by gregburek** [comment]
There is no way to disable stunnel and still use pgbouncer with this build
pack.

Why would you need to disable stunnel?

**Comment by josh-devops-center** [comment]
> Why would you need to disable stunnel?

We are doing benchmarks on heroku, and would like to compare pgbouncer vs no pgbouncer. However, we are consistently finding on the perf-l and perf-m dynos that no pgbouncer consistently has a 10-15% higher throughput.

We aren't sure exactly of this cause. One idea was to turn of SSL to measure the performance penalty.

**Comment by gregburek** [comment]
What process formation and concurrency are you using with and without
pgbouncer?

**Comment by boblozano** [comment]
In each case doing testing with a single perf-m or perf-l dyno, gunicorn , concurrency set to 8 (perf-m) or 14 (perf-l), those levels established abs best for this app in earlier tests. App is primarily python, Django. 

Load generated with jmeter, 50 to 100 threads. Single, fairly heavy query via a post request. 

Same setup with and without pgbouncer.

**Comment by gregburek** [comment]
A few issues:

SSL is required by Heroku Postgres for all connections not coming from 10.0.0.0/8. Given the inconsistency of AWS DNS and networking, we recommend using SSL at all times. Also, I am doubtful that SSL is your bottleneck, as explored below.

PGBouncer with default settings from this buildpack, will serialize transactions over a single connection and in effect, creates a queue of db transactions. It is expected this configuration and formation will produce a performance penalty when comparing a single dyno with set concurrency and app level pg pooling to the identical dyno and app with pgbouncer/stunnel. If you wish to remove queueing for the purposes of this test, use `PGBOUNCER_DEFAULT_POOL_SIZE` >= number of workers. 

However, when comparing a formation of 60 perf-m dynos with concurrency 8, to 480 perf-l dynos with concurrency 14 and pgbouncer/stunnel, the pgbouncer architecture will allow for more overall throughput in your app and your database will not buckle under load. This buildpack is targeted for apps that are bumping up against a connection limit and are not able to optimize the database but still need to scale up. PGBouncer transaction pooling allows for configurable backpressure to be applied between the app and the db in order to maximize throughput with a penalty to 99 perc query latency. I question the utility of benchmarking at the single dyno level and of using this buildpack before you need it. 

Also, please note that performing significant load testing against Heroku apps without written consent is against our Acceptable Use Policy. More detail and how to get consent is detailed in item 11 of Prohibited Actions at https://www.heroku.com/policy/aup. 

Heroku has great support team that deals with these questions all the time and would be happy to guide you in architecting your app for success: https://help.heroku.com/tickets/new?q=App%20architecture
