### ISSUE TITLE
Enable stats interface?

### ISSUE THREAD

**Issue by kevinburkeshyp** [heroku/heroku-buildpack-pgbouncer#62]
I'm trying to debug unusually slow performance. Simple database reads for a single record that hit an index are taking 100-1500ms with any kind of concurrency; normally they take 13ms in the application.

I have a Heroku Postgres database set up with 200 available connections. I've configured the `node-postgres` poolSize to be set to 50, and set PGBOUNCER_DEFAULT_POOL_SIZE to 50. I'm testing the application by running `ab` with a concurrency of 25. I can observe in app-level metrics that the majority of time is being spent waiting querying the database (at least, according to the application). 

Despite having ~50 connections configured, in Postgres, `SELECT * FROM pg_stat_activity WHERE state='active'` never goes above about 7. 

I am trying to figure out whether there is some kind of bottleneck I am ignoring. I am wondering if I have pgbouncer set up correctly; I'd like to log in to the admin console and run `SHOW POOLS;` to view the active and waiting connections.

Unfortunately this is difficult because I can't get access to the running application on Heroku.

Is there a way to configure a `stats_user` that would let me access the admin dashboard? Alternatively, a way to get the "LOG stats" output to print information about the pool usage?

**Comment by gregburek** [comment]
Hello, 
The stats interface is enabled by default, but connecting to a live heroku dyno via psql or ssh is not possible. I would suggest seeing if your app's connection pooling is defeating what pgbouncer should be providing.

Are you using Rails/ActiveRecord connection pooling? This may put a cap on the number of possible connections to pgbouncer that is not immediately obvious. Heroku advises raising the `:pool` count https://devcenter.heroku.com/articles/concurrency-and-database-connections#connection-pool I would further suggest drastically reducing the timeout so that you may get better feedback as to if the connection pool is your bottleneck.

Some indication as to connections from your app to pgbouncer is possible via `heroku logs -t --source app | grep LOG`. Connections from stunnel to your database look like `2015.10.14 20:58:34 LOG5[36]: Service [DATABASE_URL] connected remote server from xxx.xxx.xxx.xxx:47401` and connections from your app to pgbouncer look like `2015-10-14 20:58:34.962 26 LOG C-0xa37598: db1/user@127.0.0.1:37711 login attempt: db=db1 user=user` If your app is configured correctly, you should see 50 of each log line. 

Alternatively, you could connect to the stats interface of pgbouncer from your app and periodically log metrics, but that will be app specific and difficult to do in bash, so the buildpack is not likely to take on that dependency soon. 

Please let me know if this helps your troubleshooting.

**Comment by kevinburkeshyp** [comment]
Thanks for the note. The connection pool in the app is set higher than the number of PGBouncer connections, so we should be ok. I did more profiling - essentially doubled the number of application workers that could handle requests - and throughput doubled, so it seems like the problem is more in the application than in the database pool. 

Basically as far as I can tell Javascript uses a ton of memory and the event loop gets dog slow with any kind of concurrency. It's an embarrassing situation.

**Comment by gregburek** [comment]
Welp, stunnel and pgbouncer may contribute some to memory pressure, but I'm not sure how to profile these components of an app that may also grow as concurrency is increased. The Performance-m dynos may help your memory problems, but glad to know at least pgbouncer was working as expected as far as connections go.
