### ISSUE TITLE
Is the database.yml pool size used?

### ISSUE THREAD

**Issue by jeffblake** [heroku/heroku-buildpack-pgbouncer#72]
I understand how the PGBOUNCER_ ENV variables work, but what I'm missing is how this relates to the `pool` setting in `database.yml` aka `DB_POOL` ENV variable. I understand that other processes, like sidekiq, could use this setting... but will Puma use it for anything?

**Comment by gregburek** [comment]
ActiveRecord and Sequel attempts to run it's own pooler in ruby, which is what `pool` in `database.yml` is referring to. This additional layer of pooling interferes with and works to defeat the pgbouncer pooling that happens between ruby and the database. As detailed [here](https://devcenter.heroku.com/articles/concurrency-and-database-connections#connection-pool) errors can occur when the ruby pool size is too low, both with and without pgbouncer.

If you are using pgbouncer, you can open hundreds of connections from your app to the in-dyno pgbouncer with little overhead. I recommend setting the `pool` config to be at least the number of puma, sidekiq or other concurrent workers that could be running in a single dyno, so that no process is waiting on the ruby pooler for database access.

**Comment by jeffblake** [comment]
OK this make is making sense.

So if I'm running 5x Performance Dynos, with 15 workers and 8 threads per worker, the pool should be set to 8 such that if I receive 15*8*5 requests at once, each could get a connection. This would consume 600 connections. Which is too many (I have 400 minus 55 for sidekiq available). So I could set the pool to say 4, bringing my total connections to 300 + 55 for sidekiq. That's great, but now If I am hit with 600 requests per second, half of those requests will be issued connections, and the other half will wait until one is available.  Is this correct? Does a thread get a connection for the duration of the request, or does it get one and release one for every query to active record?

So if I want to handle 1000 requests per second, then the app needs to be super quick with database interactions, and waiting on database connections is a fact of life. This is the point where you would start looking into a read-only follower, sharding, microservices, etc. 

Setting the `PGBOUNCER_DEFAULT_POOL_SIZE` `PGBOUNCER_MIN_POOL_SIZE` can help with initial spikes in traffic by pre-creating those connections, but if the app has been running awhile then these settings become somewhat irrelevant (they only matter for boot times). 

I guess I thought that the whole point of PGBouncer was to be able to scale up tons of dyno's without hitting  the postgres connection limit. But it seems that none of the PGBouncer config settings actually control or limit the # of connections... this is determined by the `pool` in rails times # of workers.

**Comment by gregburek** [comment]
I think there is a misunderstanding where pgbouncer sits and its role in managing database connections. 

If you have five Performance dynos, each dyno will run pgbouncer. Each ruby process, no matter how many workers or threads, will connect to the pgbouncer process that is running in the dyno. This local connection can be 100 or more, as configured by `PGBOUNCER_MAX_CLIENT_CONN`.  Pgbouncer then lazily opens connections between the dyno and the database, with a maximum of `PGBOUNCER_DEFAULT_POOL_SIZE`. If a transaction is blocked for more than `PGBOUNCER_RESERVE_POOL_TIMEOUT` seconds, `PGBOUNCER_RESERVE_POOL_SIZE` will be spun up. If the ruby pooler is in the way, pgbouncer will not know a reserve pool needs to be used. 

With five Performance Dynos, each with `PGBOUNCER_DEFAULT_POOL_SIZE` of 5, and `PGBOUNCER_RESERVE_POOL_SIZE` of 5, you will have an absolute max of 50 connections to the database and up to 25, if transactions are fast and the reserve pool is not utilized. 

For instance, my production sidekiq workers run at 30 concurrency with a `PGBOUNCER_DEFAULT_POOL_SIZE` of 1, so I can run 900 workers from 30 database connections. 

> I guess I thought that the whole point of PGBouncer was to be able to scale up tons of dyno's without hitting the postgres connection limit.
 
Using the pgbouncer buildpack allows you to make your dynos highly concurrent, instead of scaling the number of dynos up.

Please file a Heroku support ticket so that we we may address specific issues with your application and clear up any questions about using this buildpack.

**Comment by jeffblake** [comment]
Thank you. It's becoming clear. I've filed a ticket for a bit of assistance.
