### ISSUE TITLE
Amazon RDS with failover

### ISSUE THREAD

**Issue by meskyanichi** [heroku/heroku-buildpack-pgbouncer#73]
Amazon RDS provides the "Multi-AZ" feature for high-availability/automatic failover. Unlike Heroku Postgres, their "DATABASE_URL" doesn't change when this event occurs (as far as I know) and they use internal routing to route new connections to the new master.

Does pgbouncer handle this situation, or do the dynos need to be restarted after failover occurs on RDS?

**Comment by gregburek** [comment]
Maybe, maybe not. If stunnel and pgbouncer lose connections, they will attempt to re-establish. However, I don't know if RDS uses vip routing with a stable private ip and hostname or it changes the private ip where a hostname resolves to. I have seen problems where apps do not re-resolve dns and will continually hit an old ip, but not yet from stunnel and pgbouncer. 

Best practice on Heroku is to crash the app if a database connection is not available, so that new dynos have the best chance of re-resolving dns and getting up to date references to RDS.
