### ISSUE TITLE
Support for postgis adapter?

### ISSUE THREAD

**Issue by mcook08** [heroku/heroku-buildpack-pgbouncer#79]
Looks like it is only designed to support postgres. I'm not terribly familiar with the differences between the two keywords - would that be a simple change to support either?

https://github.com/heroku/heroku-buildpack-pgbouncer/blob/master/bin/gen-pgbouncer-conf.sh#L65

**Comment by gregburek** [comment]
There is no practical difference between `postgres://` and `postgis://` except that the `postgis://` form tells your driver to expect a postgis interaction. Most apps use `postgres://` connection strings and set postgis drivers in code. 

Relying on `postgis://` is a really brittle way to configure your app, as the credentials issued by DBAAS providers usually use `postgres://` and you are forced to manually alter the connection string or dynamically edit it, which is not much better. 

As laid out in https://devcenter.heroku.com/articles/postgis we recommend adding a gem or configuring your database connection driver in code that is checked into source control, instead of relying on the connection string of the database being self aware enough to tell your code what to do. 

I'm -1 on this change as screwing with a postgres connection string to force lipq or driver behavior is a code smell for violations of the 12 factor app (https://12factor.net/)

**Comment by mcook08** [comment]
Thanks so much for the comprehensive answer.
