### ISSUE TITLE
A bit confused on config

### ISSUE THREAD

**Issue by 9mm** [heroku/heroku-buildpack-pgbouncer#80]
Hey,

I have a very basic question, but I'm a bit confused what to put my values at. Here is my current setup in production and I'm trying to add PGBouncer (with as few problems as possible, hence my posting here :)

I'm using rails 5.0.1. My app deals with finance, and I don't trust that it is thread-safe, so unfortunately everything is 1 thread as you will see below.

Heroku Postgres instance:
- **500** max connections

My `Procfile`:
- `worker` (PGB Disabled) - 20x dynos, 1 worker, 1 thread, 1 connection per dyno
- `clock` (PGB Disabled) - 1x dyno, 1 worker, 1 thread, 1 connection total
- `web` - 8x PL dynos, 50 rails instances per dyno, 1 thread, 1 connection

So total, without PGBouncer configuration at all, its `20 + 1 + (50 * 8) = 421 connections` (not taking into account buffer).

How should I use these numbers to configure PGBouncer? Thanks!

Here is my `database.yml`

```
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 1
  prepared_statements: false
```

`puma.rb`

```
workers Integer(ENV['WEB_CONCURRENCY'] || 2)
threads_count = 1
threads threads_count, threads_count
...
```

`initializers/que.rb`

```
Que.disable_prepared_statements = true # PGBouncer
```

**Comment by gregburek** [comment]
So why are you looking to use pgbouncer like this? Are you experiencing
ooms in Postgres or errors from too many connections or anticipating
scaling up your dynos?

Each situation would suggest if defaults are right for you or some
customization is needed.

I suggest opening a ticket with Heroku support so they may look at your app
and make a more tailored recommendation.

**Comment by 9mm** [comment]
I'm anticipating greatly scaling up dynos 

Sent from my iToaster

**Comment by gregburek** [comment]
Try the buildpack defaults and watch app/db info (https://devcenter.heroku.com/articles/metrics , https://github.com/heroku/heroku-pg-extras) to see if adjustments need to be made. The buildpack  defaults are conservative, erring on the side of fewest connections possible in order to stabilize the app and prevent app releases from hitting 500 connections, which can be common with heroku preboot and rolling restarts of dynos. 

Please open a ticket with Heroku support for specific recommendations, as each app, its load, its scaling issues and acceptable tradeoffs are different. They are also very nice people and can see low hanging fruit performance issues very quickly.
